apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/candonov/demo-app.git'
      targetRevision: HEAD
      path: chart/demo-app/
      helm:
        valueFiles:
          - $values/values-dev.yaml
    - repoURL: 'https://github.com/candonov/demo-app.git'
      targetRevision: HEAD
      ref: values
  project: default
