name: Do Something That Needs Scheduled

on:
  repository_dispatch:
    types: do-something
    
jobs:
  build:
    name: Run Some Thing
    runs-on: ubuntu-latest
    steps:
    - name: Do Something
      run: echo Doing Something...
        
    - name: Jira Login
      uses: atlassian/gajira-login@v3
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - id: find-issue
      name: Find in commit messages
      uses: atlassian/gajira-find-issue-key@v3
      with:
        string: ${{ github.ref }}
        
    - name: Comment on issue
      uses: atlassian/gajira-comment@v3
      with:
        issue: ${{ steps.find-issue.outputs.issue }}
        comment: ${{ github.event.pusher.name }} test comment

