name: Do Something That Needs Scheduled

on:
  repository_dispatch:
    types: open-pr

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag
      with:
        semver_only: true
 
    - name: Modify file
      run: |
        echo ${{ steps.get-latest-tag.outputs.tag }}
